# Generated by Django 3.1.2 on 2020-10-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20201010_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ManyToManyField(to='photos.Location'),
        ),
    ]
